trigger:
  branches:
    include:
      - master
      - releases/*
  paths:
    include:
      - api/*
    exclude:
      - ui/*

variables:
  S3_BUCKET: sw-books-builds

stages:
  - stage: Configure
    jobs:
      - job: Setup
        pool:
          vmImage: "Ubuntu-16.04" # defines runtime

  - stage: Testing
    jobs:
      - job: Linting
        steps:
          - script: |
              cd api/
              npm ci --quiet
              npm run eslint
            displayName: "Linting"
  - stage: Linting
    jobs:
      - job: Run_tests
        steps:
          - script: |
              cd api/
              npm ci --quiet
              npm run test
            displayName: "Running Tests"
  - stage: Build
    jobs:
      - job: Package_CloudFormation_Template
        steps:
          - script: |
              cd api/
              sudo pip install wheel
              sudo pip install setuptools
              sudo pip install --upgrade pip
              sudo pip install awscli --upgrade
              aws --version
              npm run recursive-install
          - task: AWSCLI@1
            inputs:
              awsCredentials: "DevOps"
              regionName: "us-east-1"
              awsCommand: "cloudformation"
              awsSubCommand: "package"
              awsArguments: "--s3-bucket $(S3_BUCKET) --output-template-file api/build/package.yml --template-file api/template.yml"
          - task: PublishPipelineArtifact@0
            inputs:
              artifactName: "sam-template"
              targetPath: "api/build/"
