trigger:
  branches:
    include:
      - master
      - releases/*
  paths:
    include:
      - api/*
    exclude:
      - ui/*

variables:
  S3_BUCKET: furry-friends-builds

stages:  
  - stage: Build
    jobs:
      - job: Package_CloudFormation_Template
        steps:
          - script: |
              cd api/
              sudo pip install wheel
              sudo pip install setuptools
              sudo pip install --upgrade pip
              sudo pip install awscli --upgrade
              aws --version
              npm run recursive-install
          - task: AWSCLI@1
            inputs:
              awsCredentials: "DevOps"
              regionName: "us-east-1"
              awsCommand: "cloudformation"
              awsSubCommand: "package"
              awsArguments: "--s3-bucket $(S3_BUCKET) --output-template-file api/build/package.yml --template-file api/template.yml"
          - task: PublishPipelineArtifact@0
            inputs:
              artifactName: "sam-template"
              targetPath: "api/build/"
