# UI Deployment Pipeline

trigger:
  branches:
    include:
      - master
      - releases/*
  paths:
    include:
      - ui/*
    exclude:
      - api/*
variables:
  S3_BUCKET: furry-friends-builds

stages:
  - stage: Configure
    jobs:
      - job: Setup
        pool:
          vmImage: "Ubuntu-16.04" # defines runtime
  - stage: Linting
    jobs:
      - job: Run_Linting
        steps:
          - script: |
              cd ui/
              npm ci --quiet
              npm run lint
            displayName: "Running Tests"
  - stage: Testing
    jobs:
      - job: Run_Tests
        steps:
          - script: |
              echo "This is the UI Build"
              cd ui/
              npm ci --quiet
              CI=true npm run test
            displayName: "Running Tests"
      - job: Build_&_Deploy_Demo
        steps:
          - script: |
              sudo pip install wheel
              sudo pip install setuptools
              sudo pip install --upgrade pip
              sudo pip install awscli --upgrade
              aws --version
              npm run build:dev
          - task: AWSCLI@1
            inputs:
              awsCredentials: "DevOps"
              regionName: "us-east-1"
              awsCommand: "s3"
              awsSubCommand: "sync"
              awsArguments: "./build/ s3://$(S3_BUCKET)"
            displayName: "Deploying Artifact"