version: 0.2
environment_variables:
  plaintext:
    "INPUT_FILE": "saml.yaml"
    "S3_BUCKET": ""
containers:
  LambdaFunctions:
    phases:
      install:
        - pip install aws-sam-cli
      during_build:
        commands:
          - aws cloudformation package --template $INPUT_FILE --s3-bucket $S3_BUCKET --output-template post-saml.yaml
    artifacts:
      files:
        - post-saml.yaml


# sam build --use-container && sam package --s3-bucket $S3_BUCKET
# - aws cloudformation package --template $INPUT_FILE --s3-bucket  --output-template post-saml.yaml
